
import '../../public/assets/vendor/bootstrap/css/bootstrap.min.css';
import '../../public/assets/vendor/bootstrap-icons/bootstrap-icons.css';
import '../../public/assets/vendor/boxicons/css/boxicons.min.css';
import '../../public/assets/vendor/quill/quill.snow.css';
import '../../public/assets/vendor/quill/quill.bubble.css';
import '../../public/assets/vendor/remixicon/remixicon.css';
import '../../public/assets/vendor/simple-datatables/style.css';
import '../../public/assets/css/style.css';
// import '../../public/assets/vendor/apexcharts/apexcharts.min.js';
// import '../../public/assets/vendor/bootstrap/js/bootstrap.bundle.min.js';
// import '../../public/assets/vendor/chart.js/chart.umd.js';
// import '../../public/assets/vendor/echarts/echarts.min.js';
// import '../../public/assets/vendor/quill/quill.min.js';
// import '../../public/assets/vendor/simple-datatables/simple-datatables.js';
// import '../../public/assets/vendor/tinymce/tinymce.min.js';
// import '../../public/assets/vendor/php-email-form/validate.js';
// import '../../public/assets/js/main.js';





import './globals.css'
import { Inter } from 'next/font/google'
import 'bootstrap/dist/css/bootstrap.css';
import Head from 'next/head';
import Script from 'next/script'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Dashboard - NiceAdmin Bootstrap Template',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>

        <link href="assets/img/apple-touch-icon.png" rel="apple-touch-icon" />


        <link href="https://fonts.gstatic.com" rel="preconnect" />
        <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Nunito:300,300i,400,400i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet" />


        <link href="assets/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
        <link href="assets/vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet" />
        <link href="assets/vendor/boxicons/css/boxicons.min.css" rel="stylesheet" />
        <link href="assets/vendor/quill/quill.snow.css" rel="stylesheet" />
        <link href="assets/vendor/quill/quill.bubble.css" rel="stylesheet" />
        <link href="assets/vendor/remixicon/remixicon.css" rel="stylesheet" />
        <link href="assets/vendor/simple-datatables/style.css" rel="stylesheet" />


        <link href="assets/css/style.css" rel="stylesheet"></link>
      </Head>
      <body className={inter.className}>{children}

        <Script src="assets/vendor/apexcharts/apexcharts.min.js"></Script>
        <Script src="assets/vendor/bootstrap/js/bootstrap.bundle.min.js"></Script>
        <Script src="assets/vendor/chart.js/chart.umd.js"></Script>
        <Script src="assets/vendor/echarts/echarts.min.js"></Script>
        <Script src="assets/vendor/quill/quill.min.js"></Script>
        <Script src="assets/vendor/simple-datatables/simple-datatables.js"></Script>
        <Script src="assets/vendor/tinymce/tinymce.min.js"></Script>
        <Script src="assets/vendor/php-email-form/validate.js"></Script>


        <Script src="assets/js/main.js"></Script>
      </body>
    </html>
  )
}
